AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for fetch function

Parameters:
  ParentStackName:
    Type: String
    Default: ""

Globals:
  Function:
    Timeout: 3

Resources:
  FetchGithubDataApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  FetchGithubDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: src/index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          GITHUB_TOKEN: !Sub ${ParentStackName}-Token
      Events:
        Contributions:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref "FetchGithubDataApiGateway"
            Path: /github
            Method: get
  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: ""
      Stage: !Ref FetchGithubDataApiGateway.Stage
      DomainName:
        Fn::ImportValue: !Sub ${ParentStackName}-DomainName
      RestApiId: !Ref FetchGithubDataApiGateway
    DependsOn: FetchGithubDataApiGateway

Outputs:
  FetchGithubDataApi:
    Description: "API Gateway endpoint URL for Prod stage for FetchGithubDataFunction function"
    Value: !Sub "https://${FetchGithubDataApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/github/"
